name: Deploy Cluster
run-name: ${{ github.actor }}
on: [push]

env:
  RESOURCE_GROUP_NAME: terraform-state
  STORAGE_ACCOUNT_NAME: tfstate
  CONTAINER_NAME: tfstate

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Terraform Setup Script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |

          STORAGE_ACCOUNT_NAME=$STORAGE_ACCOUNT_NAME$RANDOM
          # Create resource group
          az group create --name $RESOURCE_GROUP_NAME --location uksouth

          # Create storage account
          az storage account create --resource-group $RESOURCE_GROUP_NAME --name $STORAGE_ACCOUNT_NAME --sku Standard_LRS --encryption-services blob

          # Create blob container
          az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT_NAME
