name: Deploy Cluster
run-name: ${{ github.actor }}
on: [push]

env:
  RESOURCE_GROUP_NAME: terraform-state
  STORAGE_ACCOUNT_NAME: tfstate13527
  CONTAINER_NAME: tfstate

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Run Terraform Setup Script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |

          # Create resource group
          az group create --name $RESOURCE_GROUP_NAME --location uksouth

          # Create storage account
          az storage account create --resource-group $RESOURCE_GROUP_NAME --name $STORAGE_ACCOUNT_NAME --sku Standard_LRS --encryption-services blob

          # Create blob container
          az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT_NAME

  plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
  
    - name: Terraform Init
      id: init
      run: terraform init -backend-config=backend_config/dev.conf
    
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false
      
